---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/login":
    post:
      summary: Log in
      tags:
      - user session
      parameters: []
      responses:
        '200':
          description: log in
        '401':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/logout":
    delete:
      summary: " delete session"
      tags:
      - Logout
      security:
      - bearer_auth: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '401':
          description: authentication failed
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3001
